### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by iliadaili** [igorlogius/mute-unfocused-tabs#2]
Thank you for the great add on! It's very useful. The one thing that would enhance it even more for me would be the addition of a whitelist, in which I'd add sites like Spotify, so I don't have to be clicking the extension's icon everytime I'm going to hear a song and stuff.

**Comment by igorlogius** [comment]
@iliadaili 
Sure thing, i'll add a whitelist option page. 
Shouldn't take to long. Stay tuned. :)

**Comment by igorlogius** [comment]
Version 1.1.3 has been released on the AMO site. 

It includes a url regex based exclusion list (aka. whitelist) 
If a tab url matches with any entry on the list, it will not be managed by the 'mute-unfocused-tabs' extension, meaning that its mute state will not be modified (anymore) and clicking the toolbar button will have no effect in its context (aka. it is disabled) 

Note: 
To persistently store the new whitelist configuration, the "storage" permission was added.

**Comment by iliadaili** [comment]
Thank you so much!
